# Module 3: Building a shared wide table as a team

The ESICM presentation calls this the **BigTable pattern**. Here we use *shared wide table* to describe it precisely: one row per admission, with columns contributed by different analysts. It is a BigQuery table design, not the Google Cloud Bigtable product.

During the datathon, the team accumulated features in a shared table for downstream modelling. This exercise teaches that organisation, including the checks and rerun behaviour needed to make it dependable.

By the end, you should be able to define a shared schema, assign ownership, replace one analyst's results without retaining stale values, and validate the result. Run this module independently: its database is synthetic and separate from Module 2.

In [1]:
# Install the teaching helpers if this is a fresh Colab session.
# The revision is pinned so these notebooks and their helpers stay together.
import importlib.util
import subprocess
import sys

HELPER_REVISION = "56ad4d43cfebb456e302f412a22eeead0ff6f41c"
if importlib.util.find_spec("datathon_prep") is None:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q",
        "git+https://github.com/ReginaldCal/Digital-Critical-Care-Datathon-Prep.git@" + HELPER_REVISION
    ])

import pandas as pd
from IPython.display import display
from datathon_prep import Demo, Pipeline, Rules, FEATURES

demo = Demo()
print("Synthetic teaching data only. No patient database connection is made.")

Synthetic teaching data only. No patient database connection is made.

## Agree on the row and the columns

A shared table is useful when everyone agrees on what each row represents. We use one ICU admission, identified by `visit_occurrence_id`, and retain `person_id` for repeated-admission checks.

The column registry records meaning, unit, source, time window and owner. A separate status field distinguishes unfinished work from a completed query that found no usable observation. Missing values remain missing until evidence supports a different interpretation.

In [2]:
registry = pd.DataFrame([
    {'column': 'fio2_at_weaning', 'unit': '%', 'window': '2h before proxy', 'owner': 'Analyst A', 'source': 'reviewed FiO2 concepts'},
    {'column': 'sbp_at_weaning', 'unit': 'mmHg', 'window': '4h before proxy', 'owner': 'Analyst B', 'source': 'reviewed invasive BP concepts'},
])
registry

,column,unit,window,owner,source
0,fio2_at_weaning,%,2h before proxy,Analyst A,reviewed FiO2 concepts
1,sbp_at_weaning,mmHg,4h before proxy,Analyst B,reviewed invasive BP concepts

## Create a separate teaching table

`CREATE TABLE` fails if the table already exists. That is intentional. A kernel restart creates a new local database; a real shared table must not be dropped or truncated as a routine recovery step.

A new column can be added with an agreed schema migration. It does not require deleting everyone's data.

In [3]:
demo.query("""
CREATE TABLE work.team_features (
  visit_occurrence_id INT64, person_id INT64,
  fio2_at_weaning FLOAT64, fio2_at_weaning_time TIMESTAMP,
  sbp_at_weaning FLOAT64, sbp_at_weaning_time TIMESTAMP,
  fio2_status STRING
)
""")
demo.query("""
INSERT INTO work.team_features (visit_occurrence_id, person_id, fio2_status)
SELECT visit_occurrence_id, person_id, 'not_started'
FROM source.visit_occurrence
""")
demo.assert_unique('work.team_features')
demo.table('work.team_features').head()

,visit_occurrence_id,person_id,fio2_at_weaning,fio2_at_weaning_time,sbp_at_weaning,sbp_at_weaning_time,fio2_status
0,101,1,NaN,NaT,NaN,NaT,not_started
1,102,1,NaN,NaT,NaN,NaT,not_started
2,201,2,NaN,NaT,NaN,NaT,not_started
3,301,3,NaN,NaT,NaN,NaT,not_started
4,401,4,NaN,NaT,NaN,NaT,not_started

## Calculate first, then publish assigned columns

Analyst A calculates a feature in a separate staging table, validates it, and publishes only their assigned columns. Analyst B can develop their calculation independently. Actual writes to the shared BigQuery table should be coordinated: different columns do not guarantee conflict-free concurrent mutations.

The dependency order is: admissions and landmarks, independent feature calculations, then derived features. A slope must wait for both input columns. BigQuery may queue or retry conflicting writes; that is different from saying the design has no conflicts.

In [4]:
# Prepare the same synthetic cohort used in Module 2.
plan = Pipeline(prefix='team_inputs')
for step, sql in plan.steps():
    demo.query(sql)

demo.query("""
CREATE TABLE work.fio2_staging AS
SELECT visit_occurrence_id, value, measured_at
FROM work.team_inputs_features WHERE feature = 'fio2' AND landmark = 'weaning'
""")
demo.assert_unique('work.fio2_staging')
demo.table('work.fio2_staging')

   visit_occurrence_id  value measured_at
0                  501   35.0  2026-01-03
1                  201   35.0  2026-01-03
2                  801   35.0  2026-01-03
3                  101   35.0  2026-01-03
4                 1001   35.0  2026-01-03
5                  701   35.0  2026-01-03
6                 1201   35.0  2026-01-03
7                  301   35.0  2026-01-03
8                  401   35.0  2026-01-03
9                 1101   35.0  2026-01-03

## Make replacement include rows with no new value

An update that only touches matching rows can leave an old, wrong value behind when a corrected unit filter removes that patient's match. The update below starts with every target admission and left-joins the new results. That replaces missing matches with NULL.

Both tables must have unique, non-null admission IDs. If multiple candidates remain, resolve them deterministically before publishing. Only the owner of these columns should run this replacement.

In [5]:
from datathon_prep.queries import replacement_update

publish = replacement_update('work.team_features', 'work.fio2_staging', 'fio2_at_weaning')
print(publish)
demo.assert_unique('work.team_features')
demo.assert_unique('work.fio2_staging')
demo.query(publish)
demo.query("""UPDATE work.team_features
SET fio2_status = CASE WHEN fio2_at_weaning IS NULL THEN 'complete_no_value' ELSE 'complete_value' END
WHERE TRUE""")
demo.table('work.team_features')[['visit_occurrence_id', 'fio2_at_weaning', 'fio2_status']]

UPDATE `work.team_features` t
SET fio2_at_weaning = s.value, fio2_at_weaning_time = s.measured_at
FROM (
 SELECT c.visit_occurrence_id, f.value, f.measured_at
 FROM `work.team_features` c
 LEFT JOIN `work.fio2_staging` f USING (visit_occurrence_id)
) s
WHERE t.visit_occurrence_id = s.visit_occurrence_id

    visit_occurrence_id  fio2_at_weaning        fio2_status
0                   101             35.0     complete_value
1                   102              NaN  complete_no_value
2                   201             35.0     complete_value
3                   301             35.0     complete_value
4                   401             35.0     complete_value
5                   501             35.0     complete_value
6                   601              NaN  complete_no_value
7                   701             35.0     complete_value
8                   801             35.0     complete_value
9                   901              NaN  complete_no_value
10                 1001             35.0     complete_value
11                 1101             35.0     complete_value
12                 1201             35.0     complete_value

A deterministic calculation on an unchanged input should produce the same result when repeated. That is the useful form of idempotency here. Changing an input, a filter or a time window can change the result and requires rerunning dependent calculations.

The next example simulates correcting a query so admission 101 no longer has a usable FiO₂ result. The published value must become missing, while Analyst B's column remains unchanged.

In [6]:
demo.query('UPDATE work.team_features SET sbp_at_weaning = 110 WHERE visit_occurrence_id = 101')
demo.query('DELETE FROM work.fio2_staging WHERE visit_occurrence_id = 101')
demo.assert_unique('work.fio2_staging')
demo.query(publish)
demo.query("""UPDATE work.team_features
SET fio2_status = CASE WHEN fio2_at_weaning IS NULL THEN 'complete_no_value' ELSE 'complete_value' END
WHERE TRUE""")
first = demo.table('work.team_features').sort_values('visit_occurrence_id').reset_index(drop=True)
demo.query(publish)
second = demo.table('work.team_features').sort_values('visit_occurrence_id').reset_index(drop=True)
pd.testing.assert_frame_equal(first, second)
row = second.set_index('visit_occurrence_id').loc[101]
assert pd.isna(row.fio2_at_weaning) and row.sbp_at_weaning == 110
print('Repeated publish is stable; stale FiO2 cleared; BP preserved.')

Repeated publish is stable; stale FiO2 cleared; BP preserved.

## Validate before marking work complete

Inspect the row count, key uniqueness, missingness and unit-normalised range. A value inside the range can still belong to the wrong admission or time window, so inspect selected source records as well.

The missingness threshold below is an exercise setting. Agree a threshold for each real feature based on its role and recording frequency. A high missing fraction calls for review, not automatic imputation.

In [7]:
from datathon_prep.demo import check_column

result = demo.table('work.team_features')
demo.assert_unique('work.team_features')
display(pd.DataFrame([check_column(result, 'fio2_at_weaning', 21, 100)]))
display(result.groupby('fio2_status', dropna=False).size().rename('admissions').reset_index())

            column  rows  missing_fraction  out_of_range  status
0  fio2_at_weaning    13          0.307692             0  REVIEW

         fio2_status  admissions
0  complete_no_value           4
1     complete_value           9

## A workable division of labour

| Work | Owner | Depends on |
|---|---|---|
| Admission definition and landmarks | Cohort lead | Reviewed source mapping |
| Respiratory features | Analyst A | Stable admission list and landmarks |
| Laboratory features | Analyst B | Stable admission list and landmarks |
| Slopes and other derived values | Assigned analyst | Validated input features |
| Analysis snapshot | Team lead | Completed checks and agreed freeze |

Keep each calculation in version control. Record the source version, query revision and run time. Coordinate publication to the shared table and freeze a dated analysis snapshot before modelling. If a bug changes a landmark, rerun all dependent features rather than repairing one column in isolation.

The original datathon pipeline did not include this full validation layer. These checks are additions to the teaching material.

Before the next event, practise adding a second staged feature and deliberately introduce a duplicate admission ID. The uniqueness check should stop publication. Then introduce a unit mismatch and explain what would be missing in the final table.

References: [BigQuery concurrent DML](https://docs.cloud.google.com/bigquery/docs/data-manipulation-language#concurrent_jobs), [BigQuery deterministic row selection](https://docs.cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions#row_number).